// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateWallet(ctx context.Context, id uuid.UUID) error
	AutoTrustFrequentPeers(ctx context.Context, transactionCount *int32) error
	CheckNonceExists(ctx context.Context, arg CheckNonceExistsParams) (bool, error)
	ConfirmTransaction(ctx context.Context, id uuid.UUID) (Transaction, error)
	CountAuditLogs(ctx context.Context) (int64, error)
	CountAuditLogsByTable(ctx context.Context, tableName string) (int64, error)
	CountPeersByWallet(ctx context.Context, walletID uuid.UUID) (int64, error)
	CountPendingTransactions(ctx context.Context) (int64, error)
	CountSyncLogsByStatus(ctx context.Context, status SyncStatus) (int64, error)
	CountTransactionsByWallet(ctx context.Context, fromWalletID uuid.UUID) (int64, error)
	CountTrustedPeers(ctx context.Context, walletID uuid.UUID) (int64, error)
	CountWallets(ctx context.Context) (int64, error)
	// internal/database/query/audit_logs.sql
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	// internal/database/query/peers.sql
	CreatePeer(ctx context.Context, arg CreatePeerParams) (Peer, error)
	// internal/database/query/sync_logs.sql
	CreateSyncLog(ctx context.Context, arg CreateSyncLogParams) (SyncLog, error)
	// internal/database/query/transactions.sql
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	// internal/database/query/wallets.sql
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	DeactivateWallet(ctx context.Context, id uuid.UUID) error
	DecrementWalletBalance(ctx context.Context, arg DecrementWalletBalanceParams) (Wallet, error)
	DeleteOldAuditLogs(ctx context.Context, dollar_1 *string) error
	DeleteOldSyncLogs(ctx context.Context, dollar_1 *string) error
	DeletePeer(ctx context.Context, id uuid.UUID) error
	FailTransaction(ctx context.Context, id uuid.UUID) error
	GetAuditLogByID(ctx context.Context, id uuid.UUID) (AuditLog, error)
	GetBalanceHistory(ctx context.Context, arg GetBalanceHistoryParams) ([]GetBalanceHistoryRow, error)
	GetDailyTransactionSummary(ctx context.Context, fromWalletID uuid.UUID) ([]GetDailyTransactionSummaryRow, error)
	GetLargeTransactions(ctx context.Context, arg GetLargeTransactionsParams) ([]Transaction, error)
	GetPeerByID(ctx context.Context, id uuid.UUID) (Peer, error)
	GetPeerByWalletAndPeerID(ctx context.Context, arg GetPeerByWalletAndPeerIDParams) (Peer, error)
	GetRecentAuditLogs(ctx context.Context, limit int32) ([]AuditLog, error)
	GetRecentTransactions(ctx context.Context, limit int32) ([]GetRecentTransactionsRow, error)
	GetRecordHistory(ctx context.Context, arg GetRecordHistoryParams) ([]AuditLog, error)
	GetStalePeers(ctx context.Context, limit int32) ([]Peer, error)
	GetSyncLogByID(ctx context.Context, id uuid.UUID) (SyncLog, error)
	GetSyncLogsByTransaction(ctx context.Context, transactionID uuid.UUID) ([]SyncLog, error)
	GetSyncLogsByWallet(ctx context.Context, arg GetSyncLogsByWalletParams) ([]SyncLog, error)
	GetSyncStats(ctx context.Context, walletID uuid.UUID) (GetSyncStatsRow, error)
	GetSyncsNeedingRetry(ctx context.Context, arg GetSyncsNeedingRetryParams) ([]SyncLog, error)
	GetSystemStats(ctx context.Context) (GetSystemStatsRow, error)
	GetTopPeersByTransactionCount(ctx context.Context, arg GetTopPeersByTransactionCountParams) ([]Peer, error)
	GetTopPeersByVolume(ctx context.Context, arg GetTopPeersByVolumeParams) ([]GetTopPeersByVolumeRow, error)
	GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error)
	GetTransactionStats(ctx context.Context, fromWalletID uuid.UUID) (GetTransactionStatsRow, error)
	GetTransactionWithWallets(ctx context.Context, id uuid.UUID) (GetTransactionWithWalletsRow, error)
	GetTransactionsByConnectionType(ctx context.Context, arg GetTransactionsByConnectionTypeParams) ([]Transaction, error)
	GetTransactionsByDateRange(ctx context.Context, arg GetTransactionsByDateRangeParams) ([]Transaction, error)
	GetTransactionsByMetadata(ctx context.Context, arg GetTransactionsByMetadataParams) ([]Transaction, error)
	GetWalletBalance(ctx context.Context, id uuid.UUID) (pgtype.Numeric, error)
	GetWalletBalanceHistory(ctx context.Context, arg GetWalletBalanceHistoryParams) ([]GetWalletBalanceHistoryRow, error)
	GetWalletByDeviceID(ctx context.Context, deviceID *string) (Wallet, error)
	GetWalletByID(ctx context.Context, id uuid.UUID) (Wallet, error)
	GetWalletByPhoneNumber(ctx context.Context, phoneNumber string) (Wallet, error)
	GetWalletByPublicKey(ctx context.Context, publicKey string) (Wallet, error)
	// internal/database/query/utils.sql
	GetWalletDashboard(ctx context.Context, id uuid.UUID) (GetWalletDashboardRow, error)
	GetWalletWithBalance(ctx context.Context, id uuid.UUID) (GetWalletWithBalanceRow, error)
	GetWalletsNeedingSync(ctx context.Context, limit int32) ([]Wallet, error)
	HardDeletePeer(ctx context.Context, id uuid.UUID) error
	HardDeleteWallet(ctx context.Context, id uuid.UUID) error
	IncrementPeerTransactionCount(ctx context.Context, arg IncrementPeerTransactionCountParams) error
	IncrementWalletBalance(ctx context.Context, arg IncrementWalletBalanceParams) (Wallet, error)
	ListActiveWallets(ctx context.Context, arg ListActiveWalletsParams) ([]Wallet, error)
	ListAllPendingSyncs(ctx context.Context, arg ListAllPendingSyncsParams) ([]SyncLog, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByAction(ctx context.Context, arg ListAuditLogsByActionParams) ([]AuditLog, error)
	ListAuditLogsByDateRange(ctx context.Context, arg ListAuditLogsByDateRangeParams) ([]AuditLog, error)
	ListAuditLogsByIP(ctx context.Context, arg ListAuditLogsByIPParams) ([]AuditLog, error)
	ListAuditLogsByRecord(ctx context.Context, arg ListAuditLogsByRecordParams) ([]AuditLog, error)
	ListAuditLogsByTable(ctx context.Context, arg ListAuditLogsByTableParams) ([]AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error)
	ListConflictedSyncs(ctx context.Context, arg ListConflictedSyncsParams) ([]SyncLog, error)
	ListFailedSyncs(ctx context.Context, arg ListFailedSyncsParams) ([]SyncLog, error)
	ListPeersByConnectionType(ctx context.Context, arg ListPeersByConnectionTypeParams) ([]Peer, error)
	ListPeersByWallet(ctx context.Context, arg ListPeersByWalletParams) ([]Peer, error)
	ListPendingSyncs(ctx context.Context, arg ListPendingSyncsParams) ([]ListPendingSyncsRow, error)
	ListPendingTransactions(ctx context.Context, arg ListPendingTransactionsParams) ([]Transaction, error)
	ListReceivedTransactions(ctx context.Context, arg ListReceivedTransactionsParams) ([]Transaction, error)
	ListRecentPeers(ctx context.Context, arg ListRecentPeersParams) ([]Peer, error)
	ListSentTransactions(ctx context.Context, arg ListSentTransactionsParams) ([]Transaction, error)
	ListTransactionsByStatus(ctx context.Context, arg ListTransactionsByStatusParams) ([]Transaction, error)
	ListTransactionsByWallet(ctx context.Context, arg ListTransactionsByWalletParams) ([]ListTransactionsByWalletRow, error)
	ListTrustedPeers(ctx context.Context, walletID uuid.UUID) ([]Peer, error)
	ListUnsyncedTransactions(ctx context.Context, arg ListUnsyncedTransactionsParams) ([]Transaction, error)
	ListWallets(ctx context.Context, arg ListWalletsParams) ([]Wallet, error)
	MarkSettleConflict(ctx context.Context, arg MarkSettleConflictParams) (SyncLog, error)
	MarkSettleFailed(ctx context.Context, arg MarkSettleFailedParams) (SyncLog, error)
	MarkSettleSuccessful(ctx context.Context, id uuid.UUID) (SyncLog, error)
	MarkTransactionSettled(ctx context.Context, id uuid.UUID) (Transaction, error)
	ResolveSyncConflict(ctx context.Context, id uuid.UUID) (SyncLog, error)
	SearchTransactions(ctx context.Context, arg SearchTransactionsParams) ([]SearchTransactionsRow, error)
	SearchWalletsByName(ctx context.Context, arg SearchWalletsByNameParams) ([]SearchWalletsByNameRow, error)
	SearchWalletsByPhoneNumber(ctx context.Context, arg SearchWalletsByPhoneNumberParams) ([]SearchWalletsByPhoneNumberRow, error)
	SetPeerTrusted(ctx context.Context, arg SetPeerTrustedParams) error
	SettingTransaction(ctx context.Context, id uuid.UUID) (Transaction, error)
	SettledTransaction(ctx context.Context, id uuid.UUID) (Transaction, error)
	SoftDeleteWallet(ctx context.Context, id uuid.UUID) error
	UpdatePeerInfo(ctx context.Context, arg UpdatePeerInfoParams) (Peer, error)
	UpdatePeerLastSeen(ctx context.Context, id uuid.UUID) error
	UpdateSyncLogStatus(ctx context.Context, arg UpdateSyncLogStatusParams) (SyncLog, error)
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error)
	UpdateWallet(ctx context.Context, arg UpdateWalletParams) (Wallet, error)
	UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (Wallet, error)
	UpdateWalletLastSync(ctx context.Context, id uuid.UUID) error
	UpdateWalletPIN(ctx context.Context, arg UpdateWalletPINParams) error
	UpsertPeer(ctx context.Context, arg UpsertPeerParams) (Peer, error)
}

var _ Querier = (*Queries)(nil)
